from __future__ import annotations

from pathlib import Path
from typing import Any

from common import (
    ApiClient,
    TestRecorder,
    base_url_arg,
    create_dev_user,
    upload_and_parse_txt,
    user_headers,
)


CASE_A_TEXT = """第一幕
阿奇：戴丽拉，你还记得我吗？
戴丽拉：我当然记得。
小雪：阿奇，你别以为这就结束了。
阿奇和戴丽拉是情侣。
小雪和阿奇是宿敌。
阿奇的声音在雨里变得很轻。
这份资料记录了第一幕的线索和真相。
主持人提醒玩家不要提前查看凶手信息。
"""

CASE_B_TEXT = """第一幕
沈秋：林晚，你为什么还回来？
林晚：因为我从来没有忘记。
白川：沈秋，你欠我的还没有结束。
沈秋和林晚是旧识。
白川和沈秋是宿敌。
沈秋的照片被夹在日记里。
主持人提醒玩家不要提前查看真相。
"""

LONG_TEXT = """第一幕
沈秋：林晚，你为什么还回来？
林晚：因为我从来没有忘记。
沈秋和林晚是旧识。
我依然爱着你，但这不是一个新角色名。
哲理、命运、时间、回忆都只是主题词。
第一幕记录了线索，真相和凶手信息需要保留。
主持人提醒玩家不要提前查看第六幕。
沈秋的照片被夹在日记里。
阿奇的声音只是证据归属结构，不是人物。
人不念和沈秋是朋友。
"""

RELATIONSHIP_ONLY_TEXT = """第一幕
纤玉和布蓝是朋友。
纤玉的房间里留下了一张照片。
"""

EXPECTED_NON_PERSON_TERMS = {
    "阿奇的声音",
    "沈秋的照片",
    "第一幕",
    "第六幕",
    "线索",
    "真相",
    "主持人",
    "玩家",
    "资料",
    "凶手信息",
    "哲理",
    "命运",
    "时间",
    "回忆",
    "我依然",
    "人不念",
    "日记",
}

STRONG_PERSON_SOURCES = {
    "current_character",
    "identity_field",
    "filename",
    "title",
    "llm_review",
}


def main() -> int:
    args = base_url_arg("Run evidence-driven character candidate extraction checks.")
    client = ApiClient(args.base_url)
    recorder = TestRecorder("candidate_extraction", args.base_url)
    user = create_dev_user(client, "v0.18.2 Candidate Extraction User")
    headers = user_headers(user["user_id"])

    try:
        result_a = run_case(
            client,
            headers,
            title="v0.18.2 Candidate Case A",
            filename="case_a_script.txt",
            text=CASE_A_TEXT,
            expected_high_persons=["阿奇", "戴丽拉", "小雪"],
            expected_relationships=["阿奇和戴丽拉是情侣", "小雪和阿奇是宿敌"],
        )
        record_case_checks(recorder, "A", result_a)

        result_b = run_case(
            client,
            headers,
            title="v0.18.2 Candidate Case B",
            filename="case_b_script.txt",
            text=CASE_B_TEXT,
            expected_high_persons=["沈秋", "林晚", "白川"],
            expected_relationships=["沈秋和林晚是旧识", "白川和沈秋是宿敌"],
        )
        record_case_checks(recorder, "B", result_b)

        long_result = run_case(
            client,
            headers,
            title="v0.18.2 Long Text Noise Case",
            filename="long_script.txt",
            text=LONG_TEXT,
            expected_high_persons=["沈秋", "林晚"],
            expected_relationships=["沈秋和林晚是旧识"],
        )
        record_long_text_checks(recorder, long_result)

        relation_only = run_case(
            client,
            headers,
            title="v0.18.2 Relationship Only Case",
            filename="relationship_only.txt",
            text=RELATIONSHIP_ONLY_TEXT,
            expected_high_persons=[],
            expected_relationships=["纤玉和布蓝是朋友"],
        )
        record_relationship_only_checks(recorder, relation_only)

        recorder.check(
            "Business logic does not contain sample-name hardcoded list",
            "KNOWN_SAMPLE_NAMES" not in Path(
                "backend/app/services/character_candidate_extractor.py"
            ).read_text(encoding="utf-8"),
        )
        recorder.check(
            "Business logic does not hardcode A/B expected names in extractor",
            all(
                name not in Path("backend/app/services/character_candidate_extractor.py").read_text(encoding="utf-8")
                for name in ["阿奇", "戴丽拉", "小雪", "沈秋", "林晚", "白川"]
            ),
        )

        low_candidate = first_low_or_non_person_candidate(relation_only["candidates"])
        batch_result = client.post(
            f"/api/projects/{relation_only['project_id']}/characters/batch-generate",
            headers=headers,
            json_body={
                "candidate_ids": [low_candidate["candidate_id"]],
                "user_persona_name": "测试用户",
                "default_relationship_hint": "根据剧本资料生成",
                "relationship_overrides": {},
            },
        )
        recorder.check(
            "Low or review-required candidate cannot be batch-generated by default",
            len(batch_result.get("generated", [])) == 0
            and len(batch_result.get("skipped", [])) == 1,
            {
                "candidate": summarize_candidate(low_candidate),
                "batch_result": batch_result,
            },
        )
    except Exception as exc:
        recorder.record_exception("candidate extraction unexpected error", exc)

    recorder.write_report("candidate_extraction_report.json")
    return 0 if not recorder.failed_cases else 1


def run_case(
    client: ApiClient,
    headers: dict[str, str],
    *,
    title: str,
    filename: str,
    text: str,
    expected_high_persons: list[str],
    expected_relationships: list[str],
) -> dict[str, Any]:
    project = client.post(
        "/api/projects",
        headers=headers,
        json_body={"title": title, "description": "", "source_type": "upload"},
    )
    upload_and_parse_txt(
        client,
        headers=headers,
        project_id=project["project_id"],
        filename=filename,
        text=text,
    )
    candidates_first = client.post(
        f"/api/projects/{project['project_id']}/candidates/extract",
        headers=headers,
    )
    candidates_second = client.post(
        f"/api/projects/{project['project_id']}/candidates/extract",
        headers=headers,
    )
    return {
        "project_id": project["project_id"],
        "candidates": candidates_second,
        "first_count": len(candidates_first),
        "second_count": len(candidates_second),
        "expected_high_persons": expected_high_persons,
        "expected_relationships": expected_relationships,
    }


def record_case_checks(recorder: TestRecorder, label: str, result: dict[str, Any]) -> None:
    candidates = result["candidates"]
    high_person_names = high_person_name_set(candidates)
    all_person_names = {
        candidate_name(candidate)
        for candidate in candidates
        if candidate["candidate_type"] == "person"
    }
    candidate_names = {candidate_name(candidate) for candidate in candidates}
    details = candidate_details(result)

    recorder.check(
        f"Case {label} expected persons are high confidence",
        set(result["expected_high_persons"]).issubset(high_person_names),
        details,
    )
    recorder.check(
        f"Case {label} forbidden terms are not person candidates",
        all(name not in all_person_names for name in EXPECTED_NON_PERSON_TERMS),
        details,
    )
    recorder.check(
        f"Case {label} X-of-Y possessive phrases are not candidates",
        all("的" not in name for name in candidate_names),
        details,
    )
    recorder.check(
        f"Case {label} repeat extraction does not duplicate candidates",
        result["first_count"] == result["second_count"],
        {"first_count": result["first_count"], "second_count": result["second_count"]},
    )
    recorder.check(
        f"Case {label} relationship_hints are short relationship sentences",
        relationships_are_short(candidates, result["expected_relationships"]),
        {
            "relationship_hints": relationship_hints(candidates),
            "expected_relationships": result["expected_relationships"],
        },
    )
    recorder.check(
        f"Case {label} reviewer is never pending",
        all((candidate.get("reviewer_status") or "") != "pending" for candidate in candidates),
        details,
    )
    recorder.check(
        f"Case {label} high confidence persons have strong evidence",
        all(has_strong_high_evidence(candidate) for candidate in candidates if is_high_person(candidate)),
        details,
    )


def record_long_text_checks(recorder: TestRecorder, result: dict[str, Any]) -> None:
    candidates = result["candidates"]
    all_person_names = {
        candidate_name(candidate)
        for candidate in candidates
        if candidate["candidate_type"] == "person"
    }
    details = candidate_details(result)
    recorder.check(
        "Long text keeps real dialogue characters as high confidence",
        {"沈秋", "林晚"}.issubset(high_person_name_set(candidates)),
        details,
    )
    recorder.check(
        "Long text filters pronoun phrase / abstract / structure / clue noise",
        all(name not in all_person_names for name in EXPECTED_NON_PERSON_TERMS),
        details,
    )
    recorder.check(
        "Long text reviewer statuses are completed",
        all(candidate.get("reviewer_status") in {"success", "rule_fallback", "manual"} for candidate in candidates),
        details,
    )


def record_relationship_only_checks(recorder: TestRecorder, result: dict[str, Any]) -> None:
    candidates = result["candidates"]
    relation_people = [
        candidate for candidate in candidates
        if candidate_name(candidate) in {"纤玉", "布蓝"}
    ]
    details = candidate_details(result)
    recorder.check(
        "Relationship sentence alone creates review candidates but not high confidence persons",
        relation_people
        and all(candidate["candidate_type"] == "person" for candidate in relation_people)
        and all(candidate["confidence_level"] != "high" for candidate in relation_people)
        and all(candidate["needs_human_review"] for candidate in relation_people),
        details,
    )
    recorder.check(
        "Relationship-only reviewer is completed",
        all(candidate.get("reviewer_status") != "pending" for candidate in candidates),
        details,
    )


def candidate_name(candidate: dict[str, Any]) -> str:
    return candidate.get("canonical_name") or candidate.get("name") or ""


def is_high_person(candidate: dict[str, Any]) -> bool:
    return candidate["candidate_type"] == "person" and candidate["confidence_level"] == "high"


def high_person_name_set(candidates: list[dict[str, Any]]) -> set[str]:
    return {candidate_name(candidate) for candidate in candidates if is_high_person(candidate)}


def relationship_hints(candidates: list[dict[str, Any]]) -> list[str]:
    return [
        hint
        for candidate in candidates
        for hint in candidate.get("relationship_hints", [])
    ]


def relationships_are_short(candidates: list[dict[str, Any]], expected_relationships: list[str]) -> bool:
    hints = relationship_hints(candidates)
    return (
        all(len(hint) <= 80 for hint in hints)
        and all(any(expected in hint for hint in hints) for expected in expected_relationships)
    )


def has_strong_high_evidence(candidate: dict[str, Any]) -> bool:
    sources = set(candidate.get("source_types") or [])
    if sources & STRONG_PERSON_SOURCES:
        return True
    if "dialogue_label" not in sources:
        return False
    return (
        int(candidate.get("dialogue_count") or 0) >= 2
        or bool(sources - {"dialogue_label", "relationship_sentence"})
        or "relationship_sentence" in sources
    )


def first_low_or_non_person_candidate(candidates: list[dict[str, Any]]) -> dict[str, Any]:
    for candidate in candidates:
        if candidate["candidate_type"] != "person" or candidate["confidence_level"] != "high" or candidate.get("needs_human_review"):
            return candidate
    raise AssertionError("No low/review-required candidate found")


def summarize_candidate(candidate: dict[str, Any]) -> dict[str, Any]:
    return {
        "name": candidate_name(candidate),
        "candidate_type": candidate.get("candidate_type"),
        "confidence_level": candidate.get("confidence_level"),
        "needs_human_review": candidate.get("needs_human_review"),
        "source_types": candidate.get("source_types"),
        "reviewer_status": candidate.get("reviewer_status"),
    }


def candidate_details(result: dict[str, Any]) -> dict[str, Any]:
    return {
        "project_id": result["project_id"],
        "expected_high_persons": result["expected_high_persons"],
        "candidates": [summarize_candidate(candidate) for candidate in result["candidates"]],
    }


if __name__ == "__main__":
    raise SystemExit(main())
